name: Move Markdown Files to Blog

on:
  push:
    paths:
      - 'src/content/draft/*.md'

jobs:
  move-markdown:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Move Markdown files
      run: |
        # Get the list of added/modified files
        FILES=$(git diff --name-only --diff-filter=A HEAD^ HEAD src/content/draft/*.md)

        for FILE in $FILES; do
          # Extract the filename without extension
          FILENAME=$(basename "$FILE" .md)

          # Create the new directory under src/content/blog/
          NEW_DIR="src/content/blog/$FILENAME"
          mkdir -p "$NEW_DIR"

          # Move the file and rename it to index.md
          git mv "$FILE" "$NEW_DIR/index.md"
        done

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add src/content/blog/
        git commit -m 'Move markdown files to blog and rename to index.md'

    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
